name: Android CD

on:
  push:
    branches:
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Update Fastlane
      run: |
        bundle install
        bundle exec fastlane -v
    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Firebase
      run: |
        npm install -g firebase-tools
    - name: Download secrets
      env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
         scripts/download_s3.sh gradle.properties > gradle.properties
         scripts/download_s3.sh google-services.json > app/google-services.json
         scripts/download_s3.sh emitron_keystore.jks > emitron_keystore.jks
    - name: Distribute app via Firebase
      env:
         FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
         FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      run: bundle exec fastlane distribute

